# Generated by Django 5.2.7 on 2025-10-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydb',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='companydb',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
